// AUTO-GENERATED by scripts/build_groeikernen_grids.py — do not edit by hand.
// Source: PDOK OGC API — CBS Wijken en Buurten 2024 (gemeenten collection).
//
// Each grid is a COLS × ROWS boolean mask of the gemeente silhouette,
// stretched to fill its own bbox (aspect-ratio NOT preserved across towns).

export type GroeikernSlug =
  'almere'
  | 'zoetermeer'
  | 'nieuwegein'
  | 'purmerend'
  | 'lelystad'
  | 'houten';

export interface GroeikernGrid {
  slug: GroeikernSlug;
  gemeentecode: string;
  label: string;
  cols: number;
  rows: number;
  /** Each cell: true = inside the gemeente, false = outside. */
  grid: readonly (readonly boolean[])[];
}

export const GRID_COLS = 18;
export const GRID_ROWS = 18;

export const GROEIKERNEN: readonly GroeikernGrid[] = [
  {
    slug: "almere",
    gemeentecode: "GM0034",
    label: "Almere",
    cols: 18,
    rows: 18,
    grid: [
      [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, false, true, true, true, false, false, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false],
    ],
  },
  {
    slug: "zoetermeer",
    gemeentecode: "GM0637",
    label: "Zoetermeer",
    cols: 18,
    rows: 18,
    grid: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    slug: "nieuwegein",
    gemeentecode: "GM0356",
    label: "Nieuwegein",
    cols: 18,
    rows: 18,
    grid: [
      [false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, false, false, false, true, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, false, false, false, false, false, true, true, false, false, false],
      [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    slug: "purmerend",
    gemeentecode: "GM0439",
    label: "Purmerend",
    cols: 18,
    rows: 18,
    grid: [
      [false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true],
      [false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false],
    ],
  },
  {
    slug: "lelystad",
    gemeentecode: "GM0995",
    label: "Lelystad",
    cols: 18,
    rows: 18,
    grid: [
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, true, true, true, true, false, false, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false],
    ],
  },
  {
    slug: "houten",
    gemeentecode: "GM0321",
    label: "Houten",
    cols: 18,
    rows: 18,
    grid: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
];
